name: Privacy Tests

on:
  push:
    branches:
      - feature/marcos/privacy_integration_tests

jobs:

  privacy_tests:
    runs-on: macos-latest
    name: Privacy Integration Tests

    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
      - name: set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-emu-30

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          ndk: 21.0.6113669
          target: google_atd
          channel: canary
          arch: x86
          profile: Nexus 5
          force-avd-creation: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Privacy Integration Tests
        uses: reactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          ndk: 21.0.6113669
          target: google_atd
          channel: canary
          arch: x86_64
          profile: Pixel 5
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew app:connectedPlayDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.annotation=com.duckduckgo.espresso.PrivacyTest -Pandroid.testInstrumentationRunnerArguments.clearPackageData=true

      - name: Bundle the Privacy Test report
        if: always()
        run: find . -type d -name 'reports' | zip -@ -r privacy-test-report.zip

      - name: Upload the Privacy Test report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: privacy-test-error-report
          path: privacy-test-report.zip